### ISSUE TITLE
4k7 resistors

### ISSUE THREAD

**Issue by davidm-public** [G6EJD/ESP8266-oximetry-and-heart-rate-sensor#1]
Hi, curious if you noticed any issues with the 4k7 resistors.

See comment at the bottom of this link: 
https://github.com/oxullo/Arduino-MAX30100

re need to resolder to Vin instead of 1.8V supply?

David

**Comment by G6EJD** [comment]
Hi Dave, I haven’t experienced any issues with operation of this device when using an ESP8266 or ESP32 both using 3.3v supplies and so I/O at 3.3v. The device uses a 1.8v supply so the breakout board has been designed correctly with pull-ups to 1.8v and I suspect this is an Arduino or ESP issue as 1.8v is barely enough to be registered as a high but adding pull ups to 3.3 or 5 would solve that. Needs level conversion really. The ESP32 has switchable pull-ups if that helps.
