### ISSUE TITLE
I cannot find the library "heartRate.h"  

### ISSUE THREAD

**Issue by boblongoria** [G6EJD/ESP8266-oximetry-and-heart-rate-sensor#2]
The code is clear enough..I am using a Wemos D1 mini just for the record based on a youtube vid in which you like its low power consumption.

 I can find easily all other libaries.

**Comment by G6EJD** [comment]
It's in the Sparkfun library for sure.

**Comment by boblongoria** [comment]
thsnks you answered me on youtube!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
